# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import event_store_pb2 as event__store__pb2


class EventStoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.publish = channel.unary_unary(
        '/eventstore.EventStore/publish',
        request_serializer=event__store__pb2.PublishRequest.SerializeToString,
        response_deserializer=event__store__pb2.PublishResponse.FromString,
        )
    self.subscribe = channel.unary_stream(
        '/eventstore.EventStore/subscribe',
        request_serializer=event__store__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=event__store__pb2.Notification.FromString,
        )
    self.unsubscribe = channel.unary_unary(
        '/eventstore.EventStore/unsubscribe',
        request_serializer=event__store__pb2.UnsubscribeRequest.SerializeToString,
        response_deserializer=event__store__pb2.UnsubscribeResponse.FromString,
        )
    self.get = channel.unary_unary(
        '/eventstore.EventStore/get',
        request_serializer=event__store__pb2.GetRequest.SerializeToString,
        response_deserializer=event__store__pb2.GetResponse.FromString,
        )


class EventStoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def publish(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def unsubscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EventStoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'publish': grpc.unary_unary_rpc_method_handler(
          servicer.publish,
          request_deserializer=event__store__pb2.PublishRequest.FromString,
          response_serializer=event__store__pb2.PublishResponse.SerializeToString,
      ),
      'subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.subscribe,
          request_deserializer=event__store__pb2.SubscribeRequest.FromString,
          response_serializer=event__store__pb2.Notification.SerializeToString,
      ),
      'unsubscribe': grpc.unary_unary_rpc_method_handler(
          servicer.unsubscribe,
          request_deserializer=event__store__pb2.UnsubscribeRequest.FromString,
          response_serializer=event__store__pb2.UnsubscribeResponse.SerializeToString,
      ),
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=event__store__pb2.GetRequest.FromString,
          response_serializer=event__store__pb2.GetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'eventstore.EventStore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
